HotelManagementService/Controllers/StatisticController.cs
using System;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using System.Web.Razor.Generator;
using HotelManagementService.DAL.Context;
using HotelManagementService.ViewModels;

namespace HotelManagementService.Controllers
{
  //[RoutePrefix("Statistic")]
  public class StatisticController : Controller
  {
    private ClientCountPerMonth[] _clientCountPerMonths = new ClientCountPerMonth[12];
    private HotelManagementContext _db = new HotelManagementContext();

    // GET: Statistic

    [HttpGet]
    //[Route("Index/{year}")]
    public ActionResult Index(int year = 2016)
    {
      SetClientsPerMonth(year);
      return View(_clientCountPerMonths);
    }

    private void SetClientsPerMonth(int year)
    {
      for (var i = 0; i < 12; i++)
      {
        var firstDayMonthPar = new SqlParameter("firstDayMonth", new DateTime(year, i + 1, 1));
        var lastMonthDayPar = new SqlParameter("lastMonthDay", new DateTime(year, i + 1, DateTime.DaysInMonth(year, i + 1)));
        _clientCountPerMonths[i] = new ClientCountPerMonth
        {
          Month = i,
          ClientCount = _db.Database.SqlQuery<int?>(@"exec CountClientPerMonth  @firstDayMonth, @lastMonthDay", firstDayMonthPar, lastMonthDayPar).First()
        };
      }
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        _db.Dispose();
      }
      base.Dispose(disposing);
    }
  }

  
//create procedure CountClientPerMonth 
//@firstDayMonth datetime2(7),
//@lastMonthDay datetime2(7)
//as
//begin
//SELECT sum(r.BEdDBCount + r.BedSBCOunt)from dbo.Events e join dbo.Room r on e.Room_Id = r.Id where e.ArriveDate between convert(datetime2,@firstDayMonth) and convert(datetime2,@lastMonthDay) or e.DepatureDate between  convert(datetime2,@firstDayMonth) and convert(datetime2,@lastMonthDay)
//end
}

HotelManagementService/Views/Statistic/Index.cshtml
@model IEnumerable<HotelManagementService.ViewModels.ClientCountPerMonth>
<style>
    .ui-datepicker-calendar { display: none; }
</style>
<section class="content">
    <div class="row">
        <div class="col-xs-6">
            <!-- BAR CHART -->
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Liczba klientów w danym miesiącu</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                       
                    </div>
                </div>
                <div class="box-body">
                    <div class="chart">
                        <canvas id="barChart" style="height: 230px"></canvas>
                    </div>
                    <div>
                        @using (Html.BeginForm("Index", "Statistic", FormMethod.Get))
                        {
                            @Html.TextBox("year", null, new {@placeholder = "Wpisz datę"})
                            <input type="submit" id="show" value="Pokaż" />
                        }                       
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
       
    </div>
</section>
@section scripts{
    @Scripts.Render("~/Scripts/chartjs/Chart.min.js")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/datetime")
    <script>
        $(document).ready(function() {
            //$("#show").click(function() {
            //    var title = $("#year").val();
            //    if (title == "" || title == null) {
            //    } else {
            //        alert("Please enter only alphanumeric values for your advertisement title");
            //    }
            //});
            $("#year").datepicker({
                changeMonth: false,
                changeYear: true,
                showButtonPanel: false,
                dateFormat: 'yy'
            });

            var data = @Html.Raw(Json.Encode(Model.Select(x => x.ClientCount.GetValueOrDefault(0))));
            var areaChartData = {
                labels: ["Styczeń", "Luty", "Marzec", "Kwiecieć", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
                datasets: [
                    {
                        label: "Electronics",
                        fillColor: "rgba(210, 214, 222, 1)",
                        strokeColor: "rgba(210, 214, 222, 1)",
                        pointColor: "rgba(210, 214, 222, 1)",
                        pointStrokeColor: "#c1c7d1",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(220,220,220,1)",
                        data: data
                    }
                ]
            };
            //-------------
            //- BAR CHART -
            //-------------
            var barChartCanvas = $("#barChart").get(0).getContext("2d");
            var barChart = new Chart(barChartCanvas);
            var barChartData = areaChartData;
            barChartData.datasets[0].fillColor = "#dd4b39";
            barChartData.datasets[0].strokeColor = "#dd4b39";
            barChartData.datasets[0].pointColor = "#dd4b39";
            var barChartOptions = {
                //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
                scaleBeginAtZero: true,
                //Boolean - Whether grid lines are shown across the chart
                scaleShowGridLines: true,
                //String - Colour of the grid lines
                scaleGridLineColor: "rgba(0,0,0,.05)",
                //Number - Width of the grid lines
                scaleGridLineWidth: 1,
                //Boolean - Whether to show horizontal lines (except X axis)
                scaleShowHorizontalLines: true,
                //Boolean - Whether to show vertical lines (except Y axis)
                scaleShowVerticalLines: true,
                //Boolean - If there is a stroke on each bar
                barShowStroke: true,
                //Number - Pixel width of the bar stroke
                barStrokeWidth: 2,
                //Number - Spacing between each of the X value sets
                barValueSpacing: 5,
                //Number - Spacing between data sets within X values
                barDatasetSpacing: 1,
                //String - A legend template
                legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].fillColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",
                //Boolean - whether to make the chart responsive
                responsive: true,
                maintainAspectRatio: true
            };

            barChartOptions.datasetFill = false;
            barChart.Bar(barChartData, barChartOptions);
        });
    </script>
    <style>
        .ui-datepicker-calendar { display: none; }
    </style>
}